### ISSUE TITLE
При проведении теста выходит ошибка

### ISSUE THREAD

**Issue by l75800** [l75800/2.3.-netology#1]
**Проблема:**
При работе с тестом происходит ошибка, скрин ошибки прикладываю. Ошибка в самом тесте не понимаю, что не так.

**Ссылка на сам проект:**
https://github.com/l75800/2.3.-netology

**Окружение**
IDEA 2019.2.4
MacOS

**Скрин:**
![error](https://user-images.githubusercontent.com/59611972/77317781-46f68500-6d25-11ea-9160-fca95ffb7ce7.png)

**Comment by ArRomanov** [comment]
Вы не инициализировали переменную `private UserModel userModel;`, поэтому у вас возникает ошибка при попытке получить значение поля `userModel.getCityPreInput()`
